### ISSUE TITLE
Future Feature Ideas

### ISSUE THREAD

**Issue by titusfortner** [titusfortner/watir_drops#1]
Here are a list of potential features. Some I am very much opposed to, some I definitely plan to do, but for most, it depends on what people want to use this gem to do. Any and all suggestions welcome.
Looking over Alister's ideas in [Roll your own page objects](http://watirmelon.com/2012/06/04/roll-your-own-page-objects/), (and firstly, I very much agree with his assessment of [Cheezy's page object gem](https://github.com/cheezy/page-object/), I see a few options.
1. Create value method similar to an element method:

``` Ruby
  element(:main_content_div) { |b| b.div(id: 'mw-content-text' ) }
  value(:main_content) { |p| p.main_content_div.text }
```

I think I'd prefer to see this implemented along the lines of:

``` Ruby
  element(:main_content_div) { |b| b.div(id: 'mw-content-text' ) }
  def main_content_value
    main_content_div.value
  end
```

Now, Watir::Elements already defines the `#value` method as `attribute_value('value') || ''`
We could override this by element to return the text or true/false for checkboxes and radio buttons according to what makes sense. This would change existing Watir behavior by returning actual information instead of an empty string (which means this method is very unlikely to be used for these elements anyway. Honestly, I kind of think that should be the default in Watir, but that's another discussion for another day.

2. Alister also used an expected_title method: `expected_title "Log out - #{Wikipedia::TITLE}"`
I think I'd prefer to see a more generic implementation along the lines of:

``` Ruby
def on_page?
  browser.url.match /title=Special:UserLogout/
end
```

This would allow you to verify that you are on your page however you'd like, as you could just as easily do: `browser.title == "Log out - #{Wikipedia::TITLE}"` or `class.elements.all? { |el| el.present? }`

2a. If it is defined for a page, make the `on_page?` method a required check at the end of using `visit` method, and at the beginning of the `use` method. This would address the often found concern of a test failing for not finding an element because the previous command did not complete correctly. It could make for a better stack trace for debugging. [test-page](https://github.com/jarmo) makes sure a navigation has happened before any elements are accessed, which is actually another place this should be checked since you can use `#new` instead of either `#use` or `#visit` when executing methods on the page object.

2b. I've also seen this aliased as `#displayed?` which might make more sense.

2c. Even better, `#visit` should do a wait for `on_page?` to be true

2d. [site_prism](https://github.com/natritmeyer/site_prism) calls this method `#load_validation` so maybe add an alias...

3. Global name spaced `#visit` and `#on` methods - nope. I don't care if it is in Cucumber World instead of actually globally name spaced, but it is definitely bad practice (<shakes fist at all of [Capybara](https://github.com/jnicklas/capybara)>. I understand the argument that "it is easier for beginners to understand" or "more readable," but at the point your framework's examples immediately show using it conjunction with functional blocks instead of an easier procedural pattern (and they all do), you're losing that argument, anyway. One of my goals is to make it easy to advance from a beginner to intermediate developer when using this code, and getting used to an actual Object Oriented approach of methods acting on objects is necessary (and not that confusing). Another goal is to keep away from a DSL that forces you into a particular approach rather than giving you a wealth of methods to pick and choose from.

4. Page Sections. I believe the need for this is obviated by being able to define the context of an element: 

``` Ruby
element(:section1) { browser.div(id: 'section1')
element(:subsection) { section1.div(id: 'subsection')
```

Additionally, I generally think of page objects as any object that takes up an entire screen (so a modal is a different page object, with a different `#goto` than the page that spawns it), or isn't always present (think most Single Page Apps where Carts and Form Fields slide open and closed, etc). In general I think it is often better to create a separate page object for them than to try to use sections. I think the same thing goes for having a separate `#iframe` class method in addition to `#element`.

5. More Alias's for `#visit` - I've seen `#load` and `#goto` in other frameworks, [Jarmo's test-page](https://github.com/jarmo/test-page) uses `#setup` so could easily add those.

6. Pass undefined methods from a Page Object onto the Browser (`#title`, `#url`, etc). Not sure if we should make that a `#define_method` or `#method_missing`

7. Ooh, I like [site_prism](https://github.com/natritmeyer/site_prism)'s `#secure?` method. Wonder if that should be in this gem or Watir.

8. It would be less brittle if, instead of getting collections like this (with pluralize):

``` Ruby
element(:name) { browser.div(class: 'name') }
```

I got collections like this:

``` Ruby
elements(:names) { browser.div(class: 'name') }
```

Both of these would be called like: `names.size`
I guess it depends on how likely you would want to define both element & elements to use the first matching as well as the list. I probably should change this one.

9. We could add some method missing magic to allow `#wait_for_name` which would be equivalent to `#name.wait_until_present`, or `#has_name?` instead of `#name.exists?`. Again, I think this is unnecessary (the less metaprogramming the better), and again, I prefer using the pattern of method calls on objects than special method calls that include the object name.

10. [Watircraft](https://github.com/bret/watircraft) creates a `#field` class method, that is distinct from the `#element` method. This might be a good idea for being more explicit about the encapsulation of the provided `#fill_form` method, but, we already know which elements are field elements based on the type of Watir::Element they are.

11. Include vs Subclass. I believe the idea of a subclass is easier for beginners to parse, and at the point that you are mixing it in to every single Page Object, I see no advantage to it.

12. I think we can add some more functionality specifically for dealing with common use cases surrounding tables and rows. [Watircraft](https://github.com/bret/watircraft/wiki/Tables) has some, [Watirmark](https://github.com/convio/watirmark/blob/master/lib/watirmark/extensions/webdriver_extensions.rb#L56) has some, etc.

13. Some people have discussed having custom assertions. I've been pretty happy using RSpec matchers in both RSpec & Cucumber, so I'm not certain what the advantages are. If we can implement something that makes error matching much easier, though, then we should definitely do it.

14. [Watirmark](https://github.com/convio/watirmark) makes a distinction between elements that are intended to be used for populating, validating, and navigating. We could have the following:

``` Ruby
element(:foo) { browser.div(id: 'foo') }
populate_element(:foo_name) { browser.text_element(id: 'name') }
validate_element(:foo_result) { browser.p(id: 'result') }
private_element(:foo_error) { browser.div(class: 'error') }
```

Populate could limit what would be allowed to be used in `#fill_form`, and Validate could be used in an `#on_page?` type condition. Element would be used for both (and could be used for everything), and Private would be for things that aren't always there and don't need to be used to input data.

15. Radio Maps. Radio elements are difficult because you can only select one, but they each have different tags in Watir.

16.  [Watirmark](https://github.com/convio/watirmark) also makes a distinction between "Controllers" and "Views" but in practice this became confusing as most methods in a controller, just passed to the view anyway. At this point, I think it is an unnecessary abstraction for the amount of utility vs obfuscation.

17. Create default behaviors for different types of elements. This is intentionally avoided. Both [Cheezy's gem](https://github.com/cheezy/page-object/) and [Watirsome](https://github.com/p0deje/watirsome) call `#click` or `#text` on various objects by default. This is one of the things that [Alister](http://watirmelon.com/2012/06/04/roll-your-own-page-objects/) and this gem specifically avoid, because it is more confusing than useful.

18. [test-page](https://github.com/jarmo/test-page) also uses `#redirect_to` in order to continue page object logic onto another Page Object. This encourages one page object to know about another which I'm not in favor of. An example is having the same page object for the Create & Edit modals since they can be exactly the same form with the exact same logic. If you rely on a form submission to return another page object, that resulting page object is often different for the different modals.

**Comment by tk8817** [comment]
RE: 4. page sections / regions

Interesting discussion happening on the watirsome repo talking about the pros/cons of site-prism & page-object's approach, along with what we would do differently. 

See the latest thoughts here: https://github.com/p0deje/watirsome/issues/9 
I have a post detailing how I envision them about half way down.

**Comment by tk8817** [comment]
Our team loves page sections specifically because you can reason about their existence / presence. When we started using them heavily, we wondered 'why don't we give our page objects the same powers?' 

We searched around and came across this interesting repo: https://github.com/jfitisoff/site-object , there are some cool ideas in there which I think you might find interesting. We don't like the approach as a whole, but certainly want to see page level reasoning in whatever we build/move to next.

**Comment by titusfortner** [comment]
After reviewing all of these ideas, I've either discounted them as not ideal, or beyond the scope of the opinionated/minimalistic approach I'm going for in this gem. The important features I've created separate issues for, and anything else can be added on an as-requested basis.
