### ISSUE TITLE
Watir 6 and selector_string

### ISSUE THREAD

**Issue by titusfortner** [titusfortner/watir_drops#4]
Gem is not properly handling usage of selector string on page objects.
Referenced here:
https://github.com/watir/watir/issues/495

**Comment by titusfortner** [comment]
@jrmartinez03 - Ok, I took a look at this and I can't repeat it. 

```
        page = TestPage.visit
        page.wait_until do
          page.language.exists? && page.language.set?
        end
```
returns this:

`NoMethodError: undefined method `wait_until' for #<TestPage:0x007f9f489e1350>`

What do you get when you use:

`page.some_element.wait_until { |el| el.exists? && el.set? }`

**Comment by jrmartinez03** [comment]
Apologies @titusfortner: my page includes Watir::Wait and Watir::Waitable
```
require 'watir_drops'

class MyPage < WatirDrops::PageObject
  include Watir::Wait
  include Watir::Waitable

  def loaded?
    true
  end
end

WatirDrops::PageObject.browser = Watir::Browser.new :phantomjs
page = MyPage.use
page.loaded? #happy
page.wait_until { page.loaded? } #not happy
```
Your alternative _does_ work.

**Comment by titusfortner** [comment]
Ah, so Watir::Waitable assumes self is either a browser or an element. If we were to define `PageObject#selector_string` it would work, but wouldn't make sense, really. 

You could do either:

`@browser.wait_until { page.loaded? }`

or I can add this to `WatirDrops::PageObject`

```
    def method_missing(method, *args, &block)
      if @browser.respond_to?(method)
        @browser.send(method, *args, &block)
      else
        super
      end
    end

    def respond_to_missing?(method, _include_all = false)
      @browser.respond_to?(method) || super
    end
```

Which would let you do:

`page.wait_until(&:loaded?)`

**Comment by jrmartinez03** [comment]
For now, my workaround is to implement selector_string in MyPage:
```
require 'watir_drops'

class MyPage < WatirDrops::PageObject
  include Watir::Wait
  include Watir::Waitable

  def selector_string
    self.class.to_s
  end

  def loaded?
    true
  end
end

WatirDrops::PageObject.browser = Watir::Browser.new :phantomjs
page = MyPage.use
page.loaded? #happy
page.wait_until { page.loaded? } #not happy
```

**Comment by titusfortner** [comment]
The point of selector_string is to give additional details on what the problem is.

Adding the `#method_missing` would give:

```
waiting for true condition on #<Watir::Browser:0x..fe317396416a2fce4 url="https://google.com" title="Google">
```

vs.

```
waiting for true condition on MyPage
```

What information would be most useful?

Also, you likely won't use this for anything directly `include Watir::Wait`

**Comment by titusfortner** [comment]
This issue should be addressed now by delegating method_missing to Watir::Browser where defined.

Additionally, I'm [pushing for changing](https://github.com/watir/watir/pull/520) `#selector_string` to `#inspect` in Watir, which makes a lot more sense all the way around, and remove the need to add a separate method in this case.
