### ISSUE TITLE
Page Verification

### ISSUE THREAD

**Issue by titusfortner** [titusfortner/watir_drops#5]
Implement: `#on_page?`

It should be able to be overridden in each subclass, and can alternately check things like page title and the presence of specific element(s).

Implement
`#title`
`#required_element`

if page_url defined then page_url?
elsif title defined, then title?
elsif required_element defined, then required_element?
else raise

possible alias: `#displayed?`, `#visible?`

Check `#on_page?` after a `#visit`?
Check `#on_page?` before using an element? before methods on the page?

Typically you want to know that the method on the previous page object has failed, not that the subsequent action on the next page object fails, so ideally evaluate `!on_page?` after form submission.

**Comment by tk8817** [comment]
Our team were just talking about implementing this. @titusfortner are you planning on building it out? Not sure if you have a design in mind, it feels pretty straightforward.

**Comment by titusfortner** [comment]
Do we want to implement a class method `#title` or `#required_element` like we do `#page_url`?

Is there an order of preference or an either/or to the methods (is `#on_page? ==> true` if it matches the `#page_url` but not the `#title`, etc)?

Do we want some kind of enforcement mechanism for being on the page? Is it on by default? How do we respect redirects?

Also, page_url definitions can be dynamic, how do we deal with checking them without that dynamic content? Should that get stored as a variable for use in being matched later?

@thekiiingbob & @abaird and I have had some conversations about this in the past, though I'm fuzzy on the details. Bob, do you remember where we ended up in that conversation we had? I think we were talking about different signatures for methods that expected to be or not to be on a page, but graphql makes my memory spotty for of that period of my life. :)

So, @tk8817 what are your minimum requirements for this? Let's implement the minimum, then discuss the ways we can use it.

**Comment by tk8817** [comment]
please see PR #8

**Comment by titusfortner** [comment]
Fixed in #8
